name: CI-CD Docker Deploy to Ubuntu EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/test_app2:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/test_app2:latest

      - name: Deploy to Ubuntu EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.UBUNTU_HOST }}
          username: ${{ secrets.UBUNTU_USER }}
          key: ${{ secrets.UBUNTU_KEY }}
          script: |
            echo "Pulling latest image"
            docker pull ${{ secrets.DOCKER_USER }}/test_app2:latest

            echo "Stopping any container using port 80"
            docker ps --filter "publish=80" -q | xargs -r docker rm -f

            echo "Starting new container"
            docker run -d \
              --name test_app2 \
              -p 80:5000 \
              ${{ secrets.DOCKER_USER }}/test_app2:latest
